version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # httpd webserver 1
  weather-report:
    image: httpd
    container_name: web1
    ports:
      - 5001:80

  # httpd webserver 2
  weather-report:
    image: httpd
    container_name: web2
    ports:
      - 5002:80
